tldr:
  botKey: YOUR_KEY_HERE
  telegramApi: https://api.telegram.org/bot
logging:
  file:
    name: logs/tldrbot.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.deolle.tldrbot.manager: DEBUG
