tldr:
  botkey: YOUR_KEY_HERE
logging:
  file:
    name: logs/tldrbot.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.deolle.tldrbot.manager: DEBUG
